# (‘▿’ʃʃ Uncomment to add your Build Plugins ƪƪ’▿’) 

[[plugins]]
package = "netlify-plugin-jamstack-conf"
  [plugins.inputs]
  triggerAll = true
  keyword = "toshi"
  databaseUrl = "https://database.com/v1/projects/1234/db/thingy"
